spring:
  application:
    name: person-api
  datasource:
    url: 'jdbc:postgresql://containers-us-west-157.railway.app:5838/railway'
    username: '${PGUSER}'
    password: '${PGPASSWORD}'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update