spring:
  application:
    name: person-api
  datasource:
    url: jdbc:h2:file:./person-api
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api